### hexo-theme-stellaris

######## head tags ########
open_graph:
  enable: true
  twitter_id: # for open_graph meta


sidebar:
  logo:
    avatar: '[https://q1.qlogo.cn/g?b=qq&nk=3526514925&s=640](/about)' # you can set avatar link in _config.yml or '[https://xxx.png](/about/)'
    title: '[config.title](/)' # you can set html tag like: '[<img no-lazy height="32px" src="xxx"/>](/)'
  menu:
    post: '[最新](/)'
    archive: '[文章](/archives/)'
    wiki: '[文档](/wiki/)'
    links: '[友链](/links/)'
    #about: # '[关于](/about/)'

  widgets:
    #### 自动生成的页面 ####
    # 主页
    home: search_blog, recent, tagcloud # for home
    # 博客索引页
    blog_index: search_blog, recent # for categories/tags/archives
    # 文档索引页
    wiki_index: search_docs, recent # for wiki
    # 其它（404）
    others: search, welcome, recent # for 404 and ...
    #### 手动创建的页面 ####
    # 文章内页
    post: toc, ghrepo, search, ghissues # for pages using 'layout:post'
    # 文档内页
    wiki: search, ghrepo, toc, ghissues, related # for pages using 'layout:wiki'
    # 其它 layout:page 的页面
    page: welcome, toc, search # for custom pages using 'layout:page'



######## Main ########
breadcrumb:
  home: home # config.title / config.author / home or custom content


######## Article ########
article:
  # 如果没有指定 excerpt 和 description，将自动取多长的内容作为文章摘要？
  auto_excerpt: 150
  # 分类颜色
  category_color:
    '模拟器': '#F58220'
    'Arch折腾记': '#35A1D7'
    '游戏': '#319D5A'
    '编程': '#940522'
    '网络': '#EEBE00'
    '日常': '#660000'
  # 文章许可协议
  license: # '本文采用 [署名-非商业性使用-相同方式共享 4.0 国际](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处。'
  # 分享
  share:  [wechat, weibo, email, link]
  # 相关文章，需要安装插件 (for layout: post)
  # npm i hexo-related-popular-posts
  related_posts:
    enable: true
    max_count: 3
    auto_cover: false


######## Comments ########
comments:
  service: valine
  valine:
    js: /cdn/js/Valine.mod.js
    appId: 'zoX8kazyGBliRB8slCeYbOMI-MdYXbMMI'
    appKey: 'ayoqJFfEYQj3teSHqfK03JJo'
    meta: [nick, mail]
    placeholder: '📨 快发条评论吧 (`･ω･´)ฅ'
    requiredFields: [nick]
    enableQQ: true # Unstable avatar link
    recordIP: false # Record commenter IP
    avatar: robohash # gravatar style https://valine.js.org/avatar
    pageSize: 10 # comment list page size
    lang: zh-cn
    highlight: true
    mathJax: false
    serverURLs: 'https://valine-api.yidaozhan.top'
    tagMeta: [博主, 小伙伴, 访客] # 标签要显示的文字,默认'博主,小伙伴,访客'
    metaPlaceholder:
      nick: "📋️ 昵称/QQ"
      mail: "📪 邮箱"
      link: "🔗 网址(https://)"
    master: #md5加密后的博主邮箱
      - 6783037F2DF30EAB99F9FC256157D875
    friends: #md5加密后的小伙伴邮箱
      - 6783037F2DF30EAB99F9FC256157D875


######## Footer ########
footer:
  social:
     - icon: '<img src="https://www.bilibili.com/favicon.ico"/>'
       url: 'https://space.bilibili.com/485832788'
     - icon: '<img src="/images/qq.svg" style="scale:0.85;top:-2px;position:relative;"/>'
       url: 'https://jq.qq.com/?_wv=1027&k=c0oqCyOm'
     - icon: '<img src="https://imgsrc.baidu.com/forum/pic/item/f603918fa0ec08fa99fb05641cee3d6d54fbda7e.png"/>'
       url: 'https://t.me/yidaozhan_group'
     - icon: '<img src="https://imgsrc.baidu.com/forum/pic/item/8326cffc1e178a8223cc6963b303738da877e805.png"/>'
       url: 'https://file.yidaozhan.top/'
     - icon: '<img src="/images/github.svg"/>'
       url: 'https://github.com/YidaozhanYa/'
  sitemap:
     '博客':
       - '[💡 近期发布](/)'
       - '[📜 历史文章](/archives)'
       - '[📊 标签](/tags)'
       - '[📗 文档](/wiki)'
       - '[🔗 友情链接](/links)'
     '网站':
       - '[🗂️️️️ 个人网盘](https://file.yidaozhan.top/)'
       - '[💸 喝了盘文件共享](https://hel.smbx.world/)'
       - '[🍄 SMBX 地图仓库](https://smbx.world/d/54-smbx)'
       - '[🏠 主页](https://yidaozhan.top)'
     '社交':
       - '[📺 Bilibili](https://space.bilibili.com/485832788)'
       - '[🐱 GitHub](https://github.com/YidaozhanYa)'
       - '[🐧 QQ](https://jq.qq.com/?_wv=1027&k=c0oqCyOm)'
       - '[🛩️ 电报](https://t.me/yidaozhan_group)'
       - '[▶️️ YouTube](https://www.youtube.com/channel/UC9VPn5_heoBDCOglDqeuuiA)'
     '其它':
       - '[🏠 首页](https://yidaozhan.top/)'
       - '[📈 状态监控](https://status.yidaozhan.top/)'
       - '[🗞️ 频道](https://t.me/s/yidaozhan_channel)'
       - '[🚇 开往•友链接力](https://www.travellings.cn/go.html)'
  license: '[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)'
  source: '[⛩ 萌ICP备20212688号](https://icp.gov.moe/?keyword=20212688)'


######## Tag Plugins ########
tag_plugins:
  # {% note text %}
  note:
    default_color: '' # light, dark, red, orange, yellow, green, cyan, blue, purple
  # {% checkbox %}
  checkbox:
    interactive: false # enable interactive for user
  emoji:
    default: /cdn/emoji/qq/%s.gif
    twemoji: https://twemoji.maxcdn.com/%s.svg
    qq: /cdn/emoji/qq/%s.gif
    tieba: /cdn/emoji/tieba/%s.png
  # {% image %}
  image:
    fancybox: true

######## JS Plugins ########
plugins:
  ## required plugins ##
  # jquery
#  jquery: https://cdn.bootcdn.net/ajax/libs/jquery/3.5.1/jquery.min.js
  jquery: /cdn/js/jquery.min.js

  ## lazyload plugins ##
  # fancybox
  fancybox:
    enable: true
    js: /cdn/js/fancybox.umd.js
    css: /cdn/css/fancybox.css
    #selector: .swiper-slide img,.vcontent img:not(.vemoji),article.content :not(div.article-footer) img # 多个选择器用英文逗号隔开
    selector: .swiper-slide img, .vcontent img:not(.vemoji) # 多个选择器用英文逗号隔开
  # swiper
  swiper:
    enable: true
    #css: https://cdn.bootcdn.net/ajax/libs/Swiper/6.8.4/swiper-bundle.min.css
    #js: https://cdn.bootcdn.net/ajax/libs/Swiper/6.8.4/swiper-bundle.min.js
    css: /cdn/css/swiper-bundle.min.css
    js: /cdn/js/swiper-bundle.min.js

  # issues api
  sitesjs: /js/plugins/sites.js
  friendsjs: /js/plugins/friends.js

  ## optional plugins ##
  # preload
  instant_click:
    js: https://cdn.bootcdn.net/ajax/libs/instantclick/3.1.0/instantclick.min.js

  # image lazyload
  # https://www.npmjs.com/package/vanilla-lazyload
  lazyload:
    enable: true # [hexo clean && hexo s] is required after changing this value.
    #js: https://cdn.bootcdn.net/ajax/libs/vanilla-lazyload/17.3.1/lazyload.min.js
    js: /cdn/js/lazyload.min.js
    transition: blur # blur, fade

  # https://scrollrevealjs.org/api/reveal.html
  scrollreveal:
    enable: true
    #js: https://cdn.bootcdn.net/ajax/libs/scrollReveal.js/4.0.9/scrollreveal.min.js
    js: /cdn/js/scrollreveal.min.js
    distance: 8px
    duration: 500 # ms
    interval: 100 # ms
    scale: 1 # 0.1~1

style:
  darkmode: auto # auto / always / false
  theme:
    light: '#f8f8f8'
    dark: '#313438'
  animated_avatar:
    animate: auto # auto, always
    background: https://imgsrc.baidu.com/forum/pic/item/960a304e251f95caaf1452608c177f3e66095207.jpg
  codeblock:
    scrollbar: 4px
    highlightjs_theme: /cdn/css/atom-one-light.min.css
    #highlightjs_theme: https://cdn.bootcdn.net/ajax/libs/highlight.js/11.6.0/styles/atom-one-light.min.css

default:
  avatar: /images/avatar.svg
  link: /images/link.svg
  cover: /images/cover.svg
  image: /images/image.svg

search:
  service: local_search # local_search, todo...
  local_search: # 在 front-matter 中设置 indexing:false 来避免被搜索索引
    path: /search.json # 搜索文件存放位置
    content: true # 是否搜索内容
    codeblock: true # 是否搜索代码块（需要content: true)
