### hexo-theme-stellaris
stellar:
  cdn_css: https://ydz-cos.zyglq.cn/blog-static/css/main.css?v=202
  cdn_js: https://ydz-cos.zyglq.cn/blog-static/js/main.js?v=202

######## head tags ########
head:
  open_graph:
    # 启用 Open Graph 以在 Twitter 和 Telegram 等平台中获得更好的链接预览体验
    enabled: true
  twitter_id:


sidebar:
  logo:
    avatar: '[https://q1.qlogo.cn/g?b=qq&nk=3526514925&s=640](/about)' # you can set avatar link in _config.yml or '[https://xxx.png](/about/)'
    title: '[config.title](/)' # you can set html tag like: '[<img no-lazy height="32px" src="xxx"/>](/)'
  menu:
    post: '[最新](/)'
    archive: '[文章](/archives/)'
    wiki: '[文档](/wiki/)'
    links: '[友链](/links/)'
    #about: # '[关于](/about/)'

  widgets:
    #### 自动生成的页面 ####
    # 主页
    home: search_blog, recent, tagcloud # for home
    # 博客索引页
    blog_index: search_blog, recent # for categories/tags/archives
    # 文档索引页
    wiki_index: search_docs, recent # for wiki
    # 其它（404）
    others: search, recent # for 404 and ...
    #### 手动创建的页面 ####
    # 文章内页
    post: toc, ghrepo, search, ghissues # for pages using 'layout:post'
    # 文档内页
    wiki: search, ghrepo, toc, ghissues, related # for pages using 'layout:wiki'
    # 其它 layout:page 的页面
    page: toc, search # for custom pages using 'layout:page'



######## Main ########
breadcrumb:
  home: home # config.title / config.author / home or custom content


######## Article ########
article:
  # 如果没有指定 excerpt 和 description，将自动取多长的内容作为文章摘要？
  auto_excerpt: 150
  # 分类颜色
  category_color:
    '模拟器': '#F58220'
    'Arch折腾记': '#35A1D7'
    '游戏': '#319D5A'
    '编程': '#940522'
    '建站小记': '#459008'
    '网络': '#EEBE00'
    '日常': '#660000'
  # 文章许可协议
  license: '本文采用 [署名-非商业性使用-相同方式共享 4.0 国际](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处。'
  # 分享
  share:  [wechat, weibo, telegram, email, link]
  # 相关文章，需要安装插件 (for layout: post)
  # npm i hexo-related-popular-posts
  related_posts:
    enabled: true
    max_count: 3
    auto_cover: false


######## Comments ########
comments:
  service: waline
  waline:
    js: https://ydz-cos.zyglq.cn/blog-static/js/waline.umd.js?v=3
    css: https://ydz-cos.zyglq.cn/blog-static/css/waline.css?v=3
    serverURL: 'https://comments-v2.chyk.ink'
    meta: [nick, mail]
    requiredMeta: [nick]
    pageSize: 10 # comment list page size
    locale:
      placeholder: '📨 快发条评论吧 (`･ω･´)ฅ'
      nick: "📋️ 昵称/QQ"
      mail: "📪 邮箱"
      link: "🔗 网址(https://)"
    highlight: true
    mathJax: false
    search: false
    pageview: true
    turnstileKey: '0x4AAAAAAAiMFYcQhCpdwew0'


######## Footer ########
footer:
  social:
     - icon: '<img src="https://www.bilibili.com/favicon.ico"/>'
       url: 'https://space.bilibili.com/485832788'
     - icon: '<img src="/images/qq.svg" style="scale:0.85;top:-2px;position:relative;"/>'
       url: 'https://jq.qq.com/?_wv=1027&k=c0oqCyOm'
     - icon: '<img src="https://imgsrc.baidu.com/forum/pic/item/f603918fa0ec08fa99fb05641cee3d6d54fbda7e.png"/>'
       url: 'https://t.me/s/chykink'
     - icon: '<img src="https://imgsrc.baidu.com/forum/pic/item/8326cffc1e178a8223cc6963b303738da877e805.png"/>'
       url: 'https://file.chyk.ink/'
     - icon: '<img src="/images/github.svg"/>'
       url: 'https://github.com/chiyuki0325'
  sitemap:
     '博客':
       - '[💡 近期发布](/)'
       - '[📜 历史文章](/archives)'
       - '[📊 标签](/tags)'
       - '[📗 文档](/wiki)'
       - '[🗓️ 时间轴](/timeline)'
       - '[🔗 友情链接](/links)'
     '网站':
       - '[🗂️️️️ 个人网盘](https://file.chyk.ink/)'
       - '[💸 喝了盘文件共享](https://hel.smbx.world/)'
       - '[🍄 SMBX 地图仓库](https://smbx.world/d/54-smbx)'
       - '[🏠 首页](https://chyk.ink)'
     '社交':
       - '[📺 Bilibili](https://space.bilibili.com/485832788)'
       - '[🐱 GitHub](https://github.com/chiyuki0325)'
       - '[🛩️ Telegram](https://t.me/s/chiyuki_cafe)'
       - '[🐧 QQ](https://jq.qq.com/?_wv=1027&k=c0oqCyOm)'
       - '[▶️️ YouTube](https://www.youtube.com/channel/UC9VPn5_heoBDCOglDqeuuiA)'
     '其它':
       # - '[🏠 首页](https://chyk.ink/)'
       # - '[⏬ 更深处](https://inner.chyk.top/)'
       - '[📈 状态监控](https://status.chyk.ink/)'
       - '[🚇 开往•友链接力](https://www.travellings.cn/go.html)'
  license: '[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)'
  source: '[GitHub](https://github.com/chiyuki0325/blog)'
  icp: '[⛩ 萌ICP备20212688号](https://icp.gov.moe/?keyword=20212688)'


######## Tag Plugins ########
tag_plugins:
  # {% note text %}
  note:
    default_color: '' # light, dark, red, orange, yellow, green, cyan, blue, purple
  # {% checkbox %}
  checkbox:
    interactive: false # enable interactive for user
  emoji:
    default: /cdn/emoji/qq/%s.gif
    twemoji: https://twemoji.maxcdn.com/%s.svg
    qq: /cdn/emoji/qq/%s.gif
    tieba: /cdn/emoji/tieba/%s.png
  # {% image %}
  image:
    fancybox: true # true, false
    parse_markdown: true # 把 markdown 格式的图片解析成图片标签
  # bilicard
  bvideo:
    enabled: true
    image_proxy: "https://stellaris.home.chyk.ink:25678/bilibili/?url="
    video_info: "https://stellaris.home.chyk.ink:25678/bvideo_info"
  video:
    js: https://ydz-cos.zyglq.cn/blog-static/js/artplayer.min.js

######## JS Plugins ########
plugins:
  # 在头部信息中写入 dns-prefetch 和 preconnect 以加快加载
  prefetch_and_preconnect: ["https://s1.hdslb.com", "https://ydz-cos.zyglq.cn"]
  ## required plugins ##
  # jquery
  jquery: https://ydz-cos.zyglq.cn/blog-static/js/jquery.min.js

  # marked
  marked: https://ydz-cos.zyglq.cn/blog-static/js/marked.min.js

  ## lazyload plugins ##
  # fancybox
  fancybox:
    enabled: true
    js: https://ydz-cos.zyglq.cn/blog-static/js/fancybox.umd.js
    css: https://ydz-cos.zyglq.cn/blog-static/css/fancybox.css
    #selector: .swiper-slide img,.vcontent img:not(.vemoji),article.content :not(div.article-footer) img # 多个选择器用英文逗号隔开
    selector: .swiper-slide img, .vcontent img:not(.vemoji), .tag-plugin.image img # 多个选择器用英文逗号隔开

  # swiper
  swiper:
    enabled: true
    css: https://ydz-cos.zyglq.cn/blog-static/css/swiper-bundle.min.css
    js: https://ydz-cos.zyglq.cn/blog-static/js/swiper-bundle.min.js

  ## optional plugins ##
  # preload
  instant_click:
    js: https://ydz-cos.zyglq.cn/blog-static/js/instantclick.min.js

  # image lazyload
  # https://www.npmjs.com/package/vanilla-lazyload
  lazyload:
    enabled: true # [hexo clean && hexo s] is required after changing this value.
    js: https://ydz-cos.zyglq.cn/blog-static/js/lazyload.min.js
    transition: blur # blur, fade

  # https://scrollrevealjs.org/api/reveal.html
  scrollreveal:
    enabled: true
    js: https://ydz-cos.zyglq.cn/blog-static/js/scrollreveal.min.js
    distance: 20px
    duration: 350 # ms
    interval: 100 # ms
    scale: 1 # 0.1~1

  # stellar api
  stellar:
    sites: https://ydz-cos.zyglq.cn/blog-static/js/plugins/sites.js?v=199
    friends: https://ydz-cos.zyglq.cn/blog-static/js/plugins/friends.js?v=199
    ghinfo: https://ydz-cos.zyglq.cn/blog-static/js/plugins/ghinfo.js?v=199
    timeline: https://ydz-cos.zyglq.cn/blog-static/js/plugins/timeline.js?v=199
    linkcard: https://ydz-cos.zyglq.cn/blog-static/js/plugins/linkcard.js?v=199
    fcircle: https://ydz-cos.zyglq.cn/blog-static/js/plugins/fcircle.js?v=199
    bvideo: https://ydz-cos.zyglq.cn/blog-static/js/plugins/bvideo.js?v=199

  # 代码块复制按钮
  copycode:
    enabled: true
    js: https://ydz-cos.zyglq.cn/blog-static/js/plugins/copycode.js
    default_text: '复制'
    success_text: '已复制'


style:
  darkmode: auto # auto / always / false
  theme:
    light: '#f8f8f8'
    dark: '#313438'
  animated_avatar:
    animate: auto # auto, always
    background: https://imgsrc.baidu.com/forum/pic/item/960a304e251f95caaf1452608c177f3e66095207.jpg
  codeblock:
    scrollbar: 4px
    highlightjs_theme: https://ydz-cos.zyglq.cn/blog-static/css/atom-one-light.min.css
  font-size:
    root: 16px
    body: 1rem
    code: 85%
    codeblock: 0.875rem
  custom_font_css:
    enabled: true
    css: https://s1.hdslb.com/bfs/static/jinkela/long/font/regular.css

default:
  avatar: /images/avatar.svg
  link: /images/link.svg
  cover: /images/cover.svg
  image: /images/image.svg

search:
  service: local_search # local_search, todo...
  local_search: # 在 front-matter 中设置 indexing:false 来避免被搜索索引
    js: https://ydz-cos.zyglq.cn/blog-static/js/search/local_search.js
    path: /search.json # 搜索文件存放位置


api_host:
  ghapi: https://r.ydz1.gq/https://api.github.com
  ghraw: https://www.githubs.cn/raw-githubusercontent
  gist: https://r.ydz1.gq/https://gist.github.com



######## 自定义插件 ########
# inject:
  # script:
  #   # 使用 HTML 语法
  #   - '<script src="https://example.com/my_script.js" data-no-instant="true"></script>'
  #   # data-no-instant 为 InstantClick 属性，决定某脚本在页面切换时是否重新加载
  #   # 如果此脚本只需要加载一次（比如添加全局对象），那么为 true
  #   # 如果此脚本每页都需要重复加载（比如编辑页面元素或需要使用 window.onload），那么为 false
  # head:
  #   # 使用 HTML 语法
  #   - '<meta name="key" content="value"></meta>'
  #   - '<link rel="stylesheet" href="/css/1.css"></link>'
  # 由于 Stylus 的特性，暂不支持 inject CSS
  # 如果要使用自定义 CSS，请在 _source/css 下创建 css 文件
  # 之后使用上文的 head 来引入
